/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Principal.FrmIngresar_Datos;

public class FrmFormularioGeneral extends javax.swing.JFrame {

    /**
     * Creates new form SegundaInterface
     */
    public FrmFormularioGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JT_TABLA = new javax.swing.JTable();
        JBVER = new javax.swing.JButton();
        TXT_ID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JT_TABLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "APELLIDO", "PESO", "SEXO", "DEPARTAMENTO", "MUNICIPIO"
            }
        ));
        JT_TABLA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JT_TABLAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JT_TABLA);

        JBVER.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBVER.setForeground(new java.awt.Color(0, 51, 255));
        JBVER.setText("VER");
        JBVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVERActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("ACTUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(JBVER, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(TXT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBVER, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVERActionPerformed
Statement Sentencia;
     
       ResultSet rsDatos;
       String SQL = "SELECT * FROM HUMANOS";
       int Fila = 0;
       DefaultTableModel modelo;
       modelo = (DefaultTableModel) JT_TABLA.getModel();
       modelo.setNumRows(0);
       try{
           Sentencia = Datos.Conexion.createStatement();
           rsDatos = Sentencia.executeQuery(SQL);
           while(rsDatos.next()){
              modelo.addRow(new Object []{});
              JT_TABLA.setValueAt(rsDatos.getString("ID"), Fila, 0);  
              JT_TABLA.setValueAt(rsDatos.getString("NOMBRE"), Fila, 1);
              JT_TABLA.setValueAt(rsDatos.getString("APELLIDOS"), Fila, 2);
              JT_TABLA.setValueAt(rsDatos.getString("PESO"), Fila, 3); 
              JT_TABLA.setValueAt(rsDatos.getString("SEXO"), Fila, 4);
              JT_TABLA.setValueAt(rsDatos.getString("DEPARTAMENTO"), Fila, 5);   
              JT_TABLA.setValueAt(rsDatos.getString("MUNICIPIO"), Fila, 6);
              Fila++;
  
              
   }
        rsDatos.close();
         Sentencia.close();      
           } catch(Exception e){
             JOptionPane.showMessageDialog(null,"error"+ e);
  
        }
            
        
        
    }//GEN-LAST:event_JBVERActionPerformed

    private void JT_TABLAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_TABLAMouseClicked
      int Fila = JT_TABLA.getSelectedRow();
        if (Fila <0) return;
        TXT_ID.setText(JT_TABLA.getValueAt(Fila, 1).toString());  
    }//GEN-LAST:event_JT_TABLAMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Statement Sentencia;
       ResultSet rsDatos;
       FrmIngresar_Datos datos =new FrmIngresar_Datos();
       int Fila = JT_TABLA.getSelectedRow();
       if (Fila <0) return;
       FrmIngresar_Datos.TXT_IDENTIDAD.setText(JT_TABLA.getValueAt(Fila, 0).toString());
       FrmIngresar_Datos.TXT_NOMBRE.setText(JT_TABLA.getValueAt(Fila, 1).toString());
       FrmIngresar_Datos.TXT_APELLIDO.setText(JT_TABLA.getValueAt(Fila, 2).toString());
       FrmIngresar_Datos.TXT_PESO.setText(JT_TABLA.getValueAt(Fila, 3).toString());
       FrmIngresar_Datos.JCB_SEXO.setSelectedItem(JT_TABLA.getValueAt (Fila, 4).toString());
       FrmIngresar_Datos.JCB_DEPARTAMENTO.setSelectedItem(JT_TABLA.getValueAt(Fila, 5).toString());
       FrmIngresar_Datos.JCB_MUNICIPIO.setSelectedItem(JT_TABLA.getValueAt(Fila, 6).toString());
       datos.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     String SQL;
        Statement Sentencia;
        SQL = "DELETE FROM HUMANOS " + "WHERE NOMBRE = "+"'" + TXT_ID.getText()+"'";
        try{
          System.out.print(SQL);
          Sentencia = Datos.Conexion.createStatement();
          Sentencia.executeUpdate(SQL);
          JOptionPane.showMessageDialog(null, "Eliminado");
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error:" + e.getMessage() );   
        }   
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFormularioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFormularioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFormularioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFormularioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFormularioGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBVER;
    private javax.swing.JTable JT_TABLA;
    private javax.swing.JTextField TXT_ID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
